name: patinfo_venv
channels:
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - contourpy=1.3.3
  - cycler=0.11.0
  - expat=2.7.3
  - faker=37.3.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkrb5=1.21.3
  - libmpdec=4.0.0
  - libpng=1.6.50
  - libpq=17.6
  - libtiff=4.5.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openjpeg=2.5.2
  - openssl=3.0.18
  - packaging=25.0
  - pcre2=10.46
  - pillow=11.1.0
  - pip=25.3
  - pixman=0.46.4
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.13.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tornado=6.5.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - alabaster==1.0.0
      - babel==2.17.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - docutils==0.21.2
      - idna==3.11
      - imagesize==1.4.1
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - requests==2.32.5
      - roman-numerals-py==3.1.0
      - snowballstemmer==3.0.1
      - sphinx==8.2.3
      - sphinx-autodoc-typehints==3.5.2
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - tkcalendar==1.6.1
      - urllib3==2.5.0
